version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/IntellectusDB
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=clave
      - APP_ARCHIVOS_RUTA_BASE=/app/transcripciones
    volumes:
      - C:\Users\JAMES MORIARTY\Documents/Transcripciones:/app/transcripciones
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootclave
      - MYSQL_DATABASE=IntellectusDB
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=clave
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 10s
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge